In [22]:
import pandas as pd

In [23]:
df=pd.read_csv("gym_members_data_with_missing_values.csv")

In [24]:
df.head(10)

,Age,Gender,Weight (kg),Height (m),Max_BPM,Avg_BPM,Resting_BPM,Session_Duration (hours),Calories_Burned,Workout_Type,Fat_Percentage,Water_Intake (liters),Workout_Frequency (days/week),Experience_Level,BMI
0,56,Male,88.3,1.71,180,157,60,1.69,1313.0,Yoga,12.6,3.5,4,3,30.20
1,46,Female,74.9,1.53,179,151,66,1.30,883.0,HIIT,33.9,2.1,4,2,32.00
2,32,Female,68.1,1.66,167,122,54,1.11,677.0,Cardio,33.4,2.3,4,2,24.71
3,25,Male,53.2,1.70,190,164,56,0.59,532.0,Strength,28.8,2.1,3,1,18.41
4,38,Male,46.1,1.79,188,158,68,0.64,556.0,Strength,29.2,2.8,3,1,14.39
5,56,Female,58.0,1.68,168,156,74,1.59,1116.0,HIIT,15.5,2.7,5,3,20.55
6,36,Male,70.3,1.72,174,169,73,1.49,1385.0,Cardio,21.3,2.3,3,2,23.76
7,40,Female,69.7,1.51,189,141,64,1.27,895.0,Cardio,30.6,1.9,3,2,30.57
8,28,Male,121.7,1.94,185,127,52,1.03,719.0,Strength,28.9,2.6,4,2,32.34
9,28,Male,101.8,1.84,169,136,64,NaN,808.0,Cardio,29.7,2.7,3,1,30.07

In [25]:
null_count = df.isnull().sum().sum()

print(null_count)

144

In [26]:
numerical_features = ['Weight (kg)', 'Height (m)', 'Session_Duration (hours)']
categorical_features = ['Gender', 'Workout_Type']

In [27]:
for col in numerical_features:
    df[col].fillna(df[col].median(), inplace=True)

C:\Users\mmeln\AppData\Local\Temp\ipykernel_19808\353046244.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\mmeln\AppData\Local\Temp\ipykernel_19808\353046244.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\mmeln\AppData\Local\Temp\ipykernel_19808\353046244.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)

In [28]:
for col in categorical_features:
    df[col].fillna(df[col].mode()[0], inplace=True)

C:\Users\mmeln\AppData\Local\Temp\ipykernel_19808\3915280948.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)

In [29]:
df = pd.get_dummies(df, columns=categorical_features, drop_first=True)

In [31]:
for col in numerical_features:
    df[col] = (df[col] - df[col].mean()) / df[col].std()

In [33]:
print(df.head())

   Age  Weight (kg)  Height (m)  Max_BPM  Avg_BPM  Resting_BPM  \
0   56     0.711632   -0.099794      180      157           60
1   46     0.062843   -1.541869      179      151           66
2   32    -0.266394   -0.500370      167      122           54
3   25    -0.987808   -0.179909      190      164           56
4   38    -1.331570    0.541128      188      158           68

   Session_Duration (hours)  Calories_Burned  Fat_Percentage  \
0                  1.283569           1313.0            12.6
1                  0.121623            883.0            33.9
2                 -0.444452            677.0            33.4
3                 -1.993713            532.0            28.8
4                 -1.844745            556.0            29.2

   Water_Intake (liters)  Workout_Frequency (days/week)  Experience_Level  \
0                    3.5                              4                 3
1                    2.1                              4                 2
2                    2.3                              4                 2
3                    2.1                              3                 1
4                    2.8                              3                 1

     BMI  Gender_Male  Workout_Type_HIIT  Workout_Type_Strength  \
0  30.20         True              False                  False
1  32.00        False               True                  False
2  24.71        False              False                  False
3  18.41         True              False                   True
4  14.39         True              False                   True

   Workout_Type_Yoga
0               True
1              False
2              False
3              False
4              False

In [34]:
# Save the processed data to a new CSV file
output_file_path = 'processed_gym_members_data.csv'
df.to_csv(output_file_path, index=False)

output_file_path

'processed_gym_members_data.csv'